### ISSUE TITLE
Bug report in PhhTreble app

### ISSUE THREAD

**Issue by Levantosa** [TrebleDroid/treble_experimentations#80]
Reproduce : Install ims apk
Vnd,nongapp,Samsung,A14

Error:

FATAL EXCEPTION: main
Process: me.phh.treble.app, PID: 4404
java.lang.IllegalArgumentException: Can only download HTTP/HTTPS URIs:
	at android.app.DownloadManager$Request.<init>(DownloadManager.java:475)
	at me.phh.treble.app.ImsSettingsFragment.onCreatePreferences$lambda$1(ImsSettings.kt:117)
	at me.phh.treble.app.ImsSettingsFragment.$r8$lambda$iX719NWGDY-1qTpZnCtxAj5fJaU(Unknown Source:0)
	at me.phh.treble.app.ImsSettingsFragment$$ExternalSyntheticLambda1.onPreferenceClick(Unknown Source:4)
	at androidx.preference.Preference.performClick(Preference.java:1200)
	at androidx.preference.Preference.performClick(Preference.java:1182)
	at androidx.preference.Preference$1.onClick(Preference.java:182)
	at android.view.View.performClick(View.java:7659)
	at android.view.View.performClickInternal(View.java:7636)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30156)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Comment by Levantosa** [comment]
Closing due to no support for ims in exynos.
